name: Add `orange` label to new issues and pull requests
on: [issues, pull_request]
jobs:
  label:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: DataBiosphere/azul-github-labeler-action@master
      with:
        repo-token: "${{secrets.GITHUB_TOKEN}}"
        label: orange
